"""empty message

Revision ID: 01561cd01a13
Revises: bafa78383f46
Create Date: 2022-08-18 15:16:05.419486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01561cd01a13'
down_revision = 'bafa78383f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'person', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    # ### end Alembic commands ###
