"""empty message

Revision ID: 1822b4ece04e
Revises: 1661dea4ac20
Create Date: 2022-10-17 19:33:39.858174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1822b4ece04e'
down_revision = '1661dea4ac20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('departments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'departments')
    # ### end Alembic commands ###
