"""empty message

Revision ID: 247b4a92ddae
Revises: 1822b4ece04e
Create Date: 2022-10-17 19:43:24.343090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247b4a92ddae'
down_revision = '1822b4ece04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('school', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('school', 'slug')
    # ### end Alembic commands ###
