"""empty message

Revision ID: 2868d00e94ff
Revises: 372e97219c89
Create Date: 2022-09-14 16:11:14.634919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2868d00e94ff'
down_revision = '372e97219c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    op.add_column('user', sa.Column('image_file', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image_file')
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('primary_phone_number', sa.INTEGER(), nullable=True),
    sa.Column('secondary_phone_number', sa.INTEGER(), nullable=True),
    sa.Column('next_of_kin', sa.VARCHAR(), nullable=True),
    sa.Column('marital_status', sa.VARCHAR(), nullable=True),
    sa.Column('class_designaiton', sa.VARCHAR(), nullable=True),
    sa.Column('home_address', sa.VARCHAR(), nullable=True),
    sa.Column('current_place_of_work', sa.VARCHAR(), nullable=True),
    sa.Column('health_status', sa.VARCHAR(), nullable=True),
    sa.Column('nationality', sa.VARCHAR(length=100), nullable=True),
    sa.Column('picture', sa.VARCHAR(), nullable=True),
    sa.Column('brithdate', sa.VARCHAR(), nullable=True),
    sa.Column('guardian', sa.VARCHAR(), nullable=True),
    sa.Column('status_doa', sa.VARCHAR(), nullable=True),
    sa.Column('extra_curriculum_activities', sa.VARCHAR(), nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=200), nullable=True),
    sa.Column('Othername', sa.INTEGER(), nullable=True),
    sa.Column('Primary', sa.INTEGER(), nullable=True),
    sa.Column('Other', sa.INTEGER(), nullable=True),
    sa.Column('Kin', sa.INTEGER(), nullable=True),
    sa.Column('Relationship', sa.INTEGER(), nullable=True),
    sa.Column('Home', sa.INTEGER(), nullable=True),
    sa.Column('Current', sa.INTEGER(), nullable=True),
    sa.Column('Marital', sa.VARCHAR(), nullable=True),
    sa.Column('Health', sa.VARCHAR(), nullable=True),
    sa.Column('Extra', sa.VARCHAR(), nullable=True),
    sa.Column('yearCompleted', sa.VARCHAR(length=200), nullable=True),
    sa.Column('contact', sa.VARCHAR(length=200), nullable=True),
    sa.Column('email', sa.VARCHAR(length=200), nullable=True),
    sa.Column('faculty', sa.VARCHAR(length=200), nullable=True),
    sa.Column('hallofresidence', sa.VARCHAR(length=200), nullable=True),
    sa.Column('index', sa.VARCHAR(length=10), nullable=True),
    sa.Column('password', sa.VARCHAR(length=20), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=10), nullable=True),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
