"""empty message

Revision ID: 2992c543d1f0
Revises: d494af7029b8
Create Date: 2022-08-12 20:45:06.760582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2992c543d1f0'
down_revision = 'd494af7029b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('primary_phone_number', sa.Integer(), nullable=True),
    sa.Column('secondary_phone_number', sa.Integer(), nullable=True),
    sa.Column('next_of_kin', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('class_designaiton', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('current_place_of_work', sa.String(), nullable=True),
    sa.Column('Year_group', sa.Integer(), nullable=False),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('picture', sa.String(), nullable=False),
    sa.Column('brithdate', sa.String(), nullable=True),
    sa.Column('guardian', sa.String(), nullable=True),
    sa.Column('status_doa', sa.String(), nullable=True),
    sa.Column('extra_curriculum_activities', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('program_name', sa.String(length=200), nullable=True),
    sa.Column('program_department', sa.String(), nullable=True),
    sa.Column('program_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_of_school', sa.String(length=200), nullable=True),
    sa.Column('programs', sa.String(), nullable=True),
    sa.Column('total_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('program', sa.String(length=200), nullable=True),
    sa.Column('total_number', sa.Integer(), nullable=True),
    sa.Column('people_completed', sa.Integer(), nullable=True),
    sa.Column('people_admitted', sa.Integer(), nullable=True),
    sa.Column('Year_group', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('year_group')
    op.drop_table('school')
    op.drop_table('program')
    op.drop_table('person')
    op.drop_table('login')
    # ### end Alembic commands ###
