"""empty message

Revision ID: 41ac04533cba
Revises: a54a6e3e587f
Create Date: 2022-09-12 17:57:33.363881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41ac04533cba'
down_revision = 'a54a6e3e587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=True),
    sa.Column('indexnumber', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('completed', sa.String(), nullable=True),
    sa.Column('admitted', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('hall', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('work', sa.String(), nullable=True),
    sa.Column('guardian', sa.String(), nullable=True),
    sa.Column('kin', sa.String(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('marital', sa.String(), nullable=True),
    sa.Column('health', sa.String(), nullable=True),
    sa.Column('extra', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_unique_constraint(None, 'person', ['nationality'])
    op.create_unique_constraint(None, 'person', ['contact'])
    op.create_unique_constraint(None, 'person', ['faculty'])
    op.create_unique_constraint(None, 'person', ['name'])
    op.create_unique_constraint(None, 'person', ['hallofresidence'])
    op.create_unique_constraint(None, 'person', ['password'])
    op.create_unique_constraint(None, 'person', ['email'])
    op.create_unique_constraint(None, 'person', ['yearCompleted'])
    op.create_unique_constraint(None, 'person', ['phone'])
    op.drop_column('person', 'secondary_phone_number')
    op.drop_column('person', 'index')
    op.drop_column('person', 'brithdate')
    op.drop_column('person', 'Current')
    op.drop_column('person', 'Extra')
    op.drop_column('person', 'next_of_kin')
    op.drop_column('person', 'Primary')
    op.drop_column('person', 'primary_phone_number')
    op.drop_column('person', 'class_designaiton')
    op.drop_column('person', 'Home')
    op.drop_column('person', 'health_status')
    op.drop_column('person', 'gender')
    op.drop_column('person', 'age')
    op.drop_column('person', 'picture')
    op.drop_column('person', 'Marital')
    op.drop_column('person', 'current_place_of_work')
    op.drop_column('person', 'home_address')
    op.drop_column('person', 'extra_curriculum_activities')
    op.drop_column('person', 'marital_status')
    op.drop_column('person', 'guardian')
    op.drop_column('person', 'Othername')
    op.drop_column('person', 'lastname')
    op.drop_column('person', 'username')
    op.drop_column('person', 'status_doa')
    op.drop_column('person', 'Health')
    op.drop_column('person', 'Relationship')
    op.drop_column('person', 'Kin')
    op.drop_column('person', 'Other')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('Other', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('Kin', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('Relationship', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('Health', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('status_doa', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('username', sa.VARCHAR(length=100), nullable=True))
    op.add_column('person', sa.Column('lastname', sa.VARCHAR(length=200), nullable=True))
    op.add_column('person', sa.Column('Othername', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('guardian', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('marital_status', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('extra_curriculum_activities', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('home_address', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('current_place_of_work', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('Marital', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('picture', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('age', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('gender', sa.VARCHAR(length=10), nullable=True))
    op.add_column('person', sa.Column('health_status', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('Home', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('class_designaiton', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('primary_phone_number', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('Primary', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('next_of_kin', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('Extra', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('Current', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('brithdate', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('index', sa.VARCHAR(length=10), nullable=True))
    op.add_column('person', sa.Column('secondary_phone_number', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_constraint(None, 'person', type_='unique')
    op.drop_table('user')
    # ### end Alembic commands ###
