"""empty message

Revision ID: 537f067244ed
Revises: 1f299b144384
Create Date: 2022-08-13 11:14:41.556637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537f067244ed'
down_revision = '1f299b144384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('primary_phone_number', sa.Integer(), nullable=True),
    sa.Column('secondary_phone_number', sa.Integer(), nullable=True),
    sa.Column('next_of_kin', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('class_designaiton', sa.String(), nullable=True),
    sa.Column('home_address', sa.String(), nullable=True),
    sa.Column('current_place_of_work', sa.String(), nullable=True),
    sa.Column('health_status', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('brithdate', sa.String(), nullable=True),
    sa.Column('guardian', sa.String(), nullable=True),
    sa.Column('status_doa', sa.String(), nullable=True),
    sa.Column('extra_curriculum_activities', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('program_name', sa.String(length=200), nullable=True),
    sa.Column('program_department', sa.String(), nullable=True),
    sa.Column('program_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('name_of_school', sa.String(length=200), nullable=True),
    sa.Column('programs', sa.String(), nullable=True),
    sa.Column('total_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('program', sa.String(length=200), nullable=True),
    sa.Column('total_number', sa.Integer(), nullable=True),
    sa.Column('people_completed', sa.Integer(), nullable=True),
    sa.Column('people_admitted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('year_group')
    op.drop_table('school')
    op.drop_table('program')
    op.drop_table('person')
    # ### end Alembic commands ###
