"""empty message

Revision ID: 83013540fdf1
Revises: 247b4a92ddae
Create Date: 2022-10-17 20:35:00.733280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83013540fdf1'
down_revision = '247b4a92ddae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'slug')
    # ### end Alembic commands ###
