"""empty message

Revision ID: 995dbe68cac4
Revises: 537f067244ed
Create Date: 2022-08-16 11:14:48.672575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995dbe68cac4'
down_revision = '537f067244ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'person', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='unique')
    # ### end Alembic commands ###
