"""empty message

Revision ID: a46f7b049d09
Revises: ac869bf3372c
Create Date: 2022-08-12 11:12:31.146304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46f7b049d09'
down_revision = 'ac869bf3372c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'password')
    op.drop_column('person', 'username')
    op.drop_column('person', 'email')
    op.drop_column('person', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('address', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('password', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
