"""empty message

Revision ID: ac869bf3372c
Revises: af64ee1c7348
Create Date: 2022-08-12 11:02:34.608629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac869bf3372c'
down_revision = 'af64ee1c7348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_name', sa.String(length=200), nullable=True),
    sa.Column('program_department', sa.String(), nullable=True),
    sa.Column('program_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('school',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_of_school', sa.String(length=200), nullable=True),
    sa.Column('programs', sa.String(), nullable=True),
    sa.Column('total_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('year_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=200), nullable=True),
    sa.Column('total_number', sa.Integer(), nullable=True),
    sa.Column('people_completed', sa.Integer(), nullable=True),
    sa.Column('people_admitted', sa.Integer(), nullable=True),
    sa.Column('year_group', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('gender', sa.String(length=100), nullable=True))
    op.add_column('person', sa.Column('primary_phone_number', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('secondary_phone_number', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('next_of_kin', sa.String(), nullable=True))
    op.add_column('person', sa.Column('student_id', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('person', sa.Column('class_designaiton', sa.String(), nullable=True))
    op.add_column('person', sa.Column('home_address', sa.String(), nullable=True))
    op.add_column('person', sa.Column('current_place_of_work', sa.String(), nullable=True))
    op.add_column('person', sa.Column('Year_group', sa.Integer(), nullable=True))
    op.add_column('person', sa.Column('health_status', sa.String(), nullable=True))
    op.add_column('person', sa.Column('nationality', sa.String(length=100), nullable=True))
    op.add_column('person', sa.Column('picture', sa.String(), nullable=True))
    op.add_column('person', sa.Column('brithdate', sa.String(), nullable=True))
    op.add_column('person', sa.Column('guardian', sa.String(), nullable=True))
    op.add_column('person', sa.Column('status_doa', sa.String(), nullable=True))
    op.add_column('person', sa.Column('extra_curriculum_activities', sa.String(), nullable=True))
    op.add_column('person', sa.Column('year_group', sa.Integer(), nullable=True))
    op.drop_column('person', 'username')
    op.drop_column('person', 'password')
    op.drop_column('person', 'email')
    op.drop_column('person', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('address', sa.INTEGER(), nullable=True))
    op.add_column('person', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.add_column('person', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.drop_column('person', 'year_group')
    op.drop_column('person', 'extra_curriculum_activities')
    op.drop_column('person', 'status_doa')
    op.drop_column('person', 'guardian')
    op.drop_column('person', 'brithdate')
    op.drop_column('person', 'picture')
    op.drop_column('person', 'nationality')
    op.drop_column('person', 'health_status')
    op.drop_column('person', 'Year_group')
    op.drop_column('person', 'current_place_of_work')
    op.drop_column('person', 'home_address')
    op.drop_column('person', 'class_designaiton')
    op.drop_column('person', 'marital_status')
    op.drop_column('person', 'student_id')
    op.drop_column('person', 'next_of_kin')
    op.drop_column('person', 'secondary_phone_number')
    op.drop_column('person', 'primary_phone_number')
    op.drop_column('person', 'gender')
    op.drop_table('year_group')
    op.drop_table('school')
    op.drop_table('program')
    # ### end Alembic commands ###
