"""empty message

Revision ID: af64ee1c7348
Revises: af3cbb30b559
Create Date: 2022-08-11 17:06:53.318566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af64ee1c7348'
down_revision = 'af3cbb30b559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('address', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'address')
    # ### end Alembic commands ###
