"""empty message

Revision ID: b35af1ed91c6
Revises: 
Create Date: 2022-08-11 16:32:15.431979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b35af1ed91c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password', sa.String(), nullable=True))
    op.alter_column('person', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('person', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('gender', sa.VARCHAR(), nullable=True))
    op.alter_column('person', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('person', 'password')
    # ### end Alembic commands ###
