"""empty message

Revision ID: b8a7aaf2a29a
Revises: 83013540fdf1
Create Date: 2022-10-17 21:25:30.468177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a7aaf2a29a'
down_revision = '83013540fdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'slug')
    # ### end Alembic commands ###
