"""empty message

Revision ID: d494af7029b8
Revises: 22e07c348924
Create Date: 2022-08-12 15:26:42.218346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd494af7029b8'
down_revision = '22e07c348924'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('person', 'gender',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('person', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('person', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('person', 'Year_group',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('person', 'nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('person', 'picture',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('program', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('school', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('year_group', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('year_group', sa.Column('Year_group', sa.Integer(), nullable=False))
    op.drop_column('year_group', 'year_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('year_group', sa.Column('year_group', sa.INTEGER(), nullable=True))
    op.drop_column('year_group', 'Year_group')
    op.drop_column('year_group', 'name')
    op.drop_column('school', 'name')
    op.drop_column('program', 'name')
    op.alter_column('person', 'picture',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('person', 'nationality',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('person', 'Year_group',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('person', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('person', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('person', 'gender',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('person', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
